GPU Mesa Intel(R) UHD Graphics 630 (CFL GT2) (Intel)
OpenGL 4.6 (Compatibility Profile) Mesa 21.3.2 - kisak-mesa PPA
[Atlas] Texture size is: 4096x4096 (max: 16384x16384)
Found work dir at '/home/pirate/Documents/GitHub/EvoluniaClient/'
== application started at Jan 23 2022 02:07:50
Evolunia 3.1 rev 0 (devel) made by otclient.net built on Jan 17 2022 for arch x64
ERROR: Layour evolunia-v2 doesn't exist, using default
Connecting to: evolunia.net:7171
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
GPU Mesa Intel(R) UHD Graphics 630 (CFL GT2) (Intel)
OpenGL 4.6 (Compatibility Profile) Mesa 21.3.2 - kisak-mesa PPA
[Atlas] Texture size is: 4096x4096 (max: 16384x16384)
Found work dir at '/home/pirate/Documents/GitHub/EvoluniaClient/'
== application started at Jan 23 2022 02:09:11
Evolunia 3.1 rev 0 (devel) made by otclient.net built on Jan 17 2022 for arch x64
ERROR: Layour evolunia-v2 doesn't exist, using default
Connecting to: evolunia.net:7171
Login to 176.9.2.170:7172
Login to 176.9.2.170:7172
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/bot/lunia_config/evolunia.lua"]:1: attempt to index field 'game_luniabot' (a nil value)
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Login to 176.9.2.170:7172
Exiting application..
ERROR: [BOT] [string "/Core/Bot/Cave/Collecting.lua"]:3: attempt to index field 'game_luniabot' (a nil value)
Exiting application..
GPU Mesa Intel(R) UHD Graphics 630 (CFL GT2) (Intel)
OpenGL 4.6 (Compatibility Profile) Mesa 21.3.2 - kisak-mesa PPA
[Atlas] Texture size is: 4096x4096 (max: 16384x16384)
Found work dir at '/home/pirate/Documents/GitHub/EvoluniaClient/'
== application started at Jan 23 2022 02:10:22
Evolunia 3.1 rev 0 (devel) made by otclient.net built on Jan 17 2022 for arch x64
ERROR: Layour evolunia-v2 doesn't exist, using default
ERROR: failed to load UI from 'luniaBot.otui': unable to open file '/modules/otcbot-master/luniaBot.otui': not found
Connecting to: evolunia.net:7171
Login to 176.9.2.170:7172
Login to 176.9.2.170:7172
